Array ( 
	[derival] => Array ( 
		[terminal] => Петрозаводск 
		[city] => Петрозаводск 
		[terminals] => Array ( 
			[0] => Array ( 
				[id] => 58 
				[name] => Петрозаводск 
				[address] => Петрозаводск, Коммунистов ул., 50 
				[streetCode] => 1.0000001000071E+24 
				[price] => 0 
				[default] => 1 
				[express] => 1 
				[isPVZ] => ) 
				) 
			[premium] => 0.00 
			[premiumDetails] => Array ( ) 
			[discountDetails] => Array ( ) 
			[price] => 0.00 
			[discount] => 0.00 ) 
		[intercity] => Array ( 
			[price] => 550.00 
			[discount] => 0.00 
			[discountDetails] => Array ( ) 
			[premium] => 0.00 
			[premiumDetails] => Array ( ) 
			[notify] => Array ( 
				[price] => 15.00 ) 
			[insurance_components] => Array ( 
				[term_insurance] => 36.00 
				[cargo_insurance] => 52.00 ) 
			[insurance] => 88.00 ) 
	[small] => Array ( 
		[price] => 749.00 
		[discount] => 0.00 
		[discountDetails] => Array ( ) 
		[premium] => 0.00 
		[premiumDetails] => Array ( ) 
		[notify] => Array ( 
			[price] => 15.00 ) 
		[insurance] => 52.00 
		[insurance_components] => Array ( 
			[cargo_insurance] => 52.00 ) 
		) 
	[air] => Array ( 
		[price] => 4080.00 
		[discount] => 0.00 
		[discountDetails] => Array ( ) 
		[premium] => 0.00 
		[premiumDetails] => Array ( ) 
		[notify] => Array ( 
			[price] => 15.00 ) 
		[insurance] => 370.00 
		[insurance_components] => Array ( 
			[cargo_insurance] => 370.00 ) 
		) 
	[order_dates] => Array ( 
		[pickup] => 
		[arrival_to_osp_sender] => 2021-03-09 
		[derrival_from_osp_sender] => 2021-03-10 
		[arrival_to_osp_receiver] => 2021-03-17 
		[derrival_from_osp_receiver] => ) 
	[delivery_term] => 
	[receiver_door] => 
	[price] => 653.00 
	[arrival] => Array ( 
		[terminal] => Орск 
		[city] => Орск 
		[terminals] => Array ( 
			[0] => Array ( 
				[id] => 117 
				[name] => Орск 
				[address] => Орск, Новотроицкое шоссе, 11 
				[streetCode] => 5.6000004000937E+24 
				[price] => 0 
				[default] => 1 
				[express] => 
				[isPVZ] => ) ) 
		[premium] => 0.00 
		[premiumDetails] => Array ( ) 
		[discountDetails] => Array ( ) 
		[price] => 0.00 
		[discount] => 0.00 ) 
		[insurance] => 88.00 
		[notify] => Array ( 
			[price] => 15.00 
			[discount] => 0.00 
			[discountDetails] => Array ( ) 
			[premium] => 0.00 
			[premiumDetails] => Array ( ) ) 
			[insurance_components] => Array ( 
				[cargo_insurance] => Array ( 
					[price] => 52.00 ) 
				[term_insurance] => Array ( 
					[price] => 36.00 ) 
				) 
					[time] => Array ( 
						[value] => 7 
						[nominative] => 7 дней 
						[genitive] => 7 дней ) 
	)